resolver: lts-5.16
packages:
- '.'
- location:
    git: https://github.com/meditans/hint
    commit: 0f14c7b735fc66c6c33dcaabb4b06daf3cd9ba97
  extra-dep: true
extra-deps:
- varying-0.5.0.0
flags: {}
extra-package-dbs: []
