resolver: lts-6.3
packages:
- '.'
- location:
    git: https://github.com/meditans/preprocessor.git
    commit: 7f596ec5671ae29e42b336bbc703df1ebce03842
  extra-dep: true
- location:
    git: https://github.com/meditans/hint.git
    commit: 0b52af4c79c1473b0ec9395d92cf589a8219b867
  extra-dep: true
extra-deps:
- varying-0.5.0.0
flags: {}
extra-package-dbs: []
